[general]
serverUri = 'http://localhost:8081/'
frontUri = 'http://localhost:8080/'

[db]
host = 'hostname'
user = 'user'
password = 'password'
dbName = 'dbName'

[jwt]
secretKey = 'secretKey'
expiration = 2592000
